version: '3.2'
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: docker/Dockerfile
        ports:
            - "8080:80"
        restart: always
        volumes:
            - ./frontend:/app
        links:
            - backend
        depends_on:
            - backend
        networks:
            - node_network
    backend:
        ports:
            - '3000:3000'
        restart: always
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/app
        links:
            - postgres
        depends_on:
            - postgres
        networks:
            - node_network
    postgres:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=todos
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/db.sql:/docker-entrypoint-initdb.d/database-seed.sql
        networks:
            - node_network
    adminer:
        image: "adminer"
        ports:
            - "9998:8080"
        links:
            - postgres
        depends_on:
            - postgres
        networks:
            - node_network
networks:
    node_network:
