version: '3.2'
services:
    frontend:
        container_name: "todo_frontend"
        build:
            context: ./frontend
            dockerfile: docker/Dockerfile
        ports:
            - "${FRONTEND_PORT}:80"
        restart: always
        volumes:
            - ./frontend:/app
        links:
            - backend
        depends_on:
            - backend
        networks:
            - node_network
        env_file:
            -   .env
    backend:
        container_name: "todo_backend"
        ports:
            - "${BACKEND_PORT}:3000"
        restart: always
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/app
        links:
            - postgres
        depends_on:
            - postgres
        networks:
            - node_network
        env_file:
            -   .env
    postgres:
        container_name: "todo_postgres"
        image: postgres:14.1-alpine
        restart: always
        ports:
            - "5132:5432"
        volumes:
            - ./postgres/db.sql:/docker-entrypoint-initdb.d/database-seed.sql
        networks:
            - node_network
        env_file:
            -   .env
networks:
    node_network:
